### ISSUE TITLE
Error while issuing make

### ISSUE THREAD

**Issue by Shashidhar123** [NervanaSystems/neon#178]
Hi,
Can someone help me with this issue , I have downloaded neon and then ran make but it prints this error

/bin/sh: .venv/bin/activate: No such file or directory
make: *** [.venv/bin/activate] Error 1

I am using anaconda python 2.7. So, in one documentation of how to install I executed this command
conda env create -f neon-conda-environment.yaml
But I am getting this error
ImportError: cannot import name HeaderParsingError

Regards
sd

**Comment by scttl** [comment]
Hi,

Are you on OSX?  It seems like reinstalling the `requests` python package may help:
`pip install --upgrade requests` per: 
* https://github.com/conda/conda/issues/1656
* http://stackoverflow.com/questions/32986626/python-requests-importerror-cannot-import-name-headerparsingerror

**Comment by Shashidhar123** [comment]
Thanks scttl, I will try it. I will try to give out the details on how I resolved Neon compilation and finally installed it on my machine, hoping that someone may benefit it. Actually, it took me 2 days to finally install Neon. 

How Neon was  finally installed

1. Had to switch to ubuntu 14.04 as 15.x ubuntu gave compile errors unsigned int cannot be compared to int,    so switched to 14.04 ubuntu, did not fresh install g++
2. first git cloned Neon
7. Installed Anaconda by running bash anaconda
8. Installed all external dependencies given in the http://neon.nervanasys.com/docs/latest/user_guide.html#installation
9. wget https://raw.githubusercontent.com/wleepang/sd-deep-learning/master/2015-12-02/neon-conda- environment.yaml
   conda env create -f neon-conda-environment.yaml
   source activate neon
   The above commands did not work initially on centos 6.x.But this time it worked on 14.04 ubuntu without any problems.
10. Then cd to Neon and then did make sysinstall
11. This compiled the loader and .so was created , this step was giving error on centos 6.x .
12. Executed /home/ubuntu/anaconda2/bin/python setup.py develop which created the egg.

This is how Neon was installed on my ubuntu 14.04. But the question still remains why the above steps did not work for ubuntu 15.x and Centos 6.x. Maybe somebody can write a blog on it.
Thanks
