### ISSUE TITLE
Running mnist-small.yaml example after setup - getting error

### ISSUE THREAD

**Issue by nirre1401** [NervanaSystems/neon#35]
Hi,
Just installed neon on Ubuntu 14 python 3.4 with the following command:
nir@nir-Satellite-Pro-A50-A:~/neon$ neon examples/mlp/mnist-small.yaml
and getting an error message:
Traceback (most recent call last):
  File "/home/nir/anaconda3/bin/neon", line 240, in <module>
    experiment, result, status = main()
  File "/home/nir/anaconda3/bin/neon", line 126, in main
    experiment = deserialize(args.yaml_file)
  File "/home/nir/anaconda3/lib/python3.4/site-packages/neon/util/persist.py", line 183, in deserialize
    if not isinstance(load_path, file):
NameError: name 'file' is not defined
I check in the directory - this file exists.
Appreciate your assistance
thanks N

**Comment by scttl** [comment]
Hi, thanks for catching this.  Confirmed it's a python3 compatibility bug.  We'll get cracking on fixing it, and will update once we've closed this.

**Comment by Thomas-Yang** [comment]
I also encountered this problem after setup. I am working on CentOS 6.6 with python 2.6.6.
WARNING:neon.util.persist:deserializing object from:  examples/mlp/mnist-small.yaml
Traceback (most recent call last):
  File "/usr/bin/neon", line 240, in <module>
    experiment, result, status = main()
  File "/usr/bin/neon", line 126, in main
    experiment = deserialize(args.yaml_file)
  File "/usr/lib/python2.6/site-packages/neon/util/persist.py", line 192, in deserialize
    return yaml.safe_load(load_path)
  File "/usr/lib64/python2.6/site-packages/yaml/__init__.py", line 93, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib64/python2.6/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/lib64/python2.6/site-packages/yaml/constructor.py", line 39, in get_single_data
    return self.construct_document(node)
  File "/usr/lib64/python2.6/site-packages/yaml/constructor.py", line 43, in construct_document
    data = self.construct_object(node)
  File "/usr/lib64/python2.6/site-packages/yaml/constructor.py", line 90, in construct_object
    data = constructor(self, tag_suffix, node)
  File "/usr/lib/python2.6/site-packages/neon/util/persist.py", line 134, in obj_multi_constructor
    cls = __import__(module)
  File "/usr/lib/python2.6/site-packages/neon/experiments/__init__.py", line 16, in <module>
    from neon.experiments.check_grad import GradientChecker  # noqa
  File "/usr/lib/python2.6/site-packages/neon/experiments/check_grad.py", line 22, in <module>
    from neon.datasets.synthetic import UniformRandom
  File "/usr/lib/python2.6/site-packages/neon/datasets/__init__.py", line 23, in <module>
    from neon.datasets.imageset import Imageset  # noqa
  File "/usr/lib/python2.6/site-packages/neon/datasets/imageset.py", line 55
    lbl_macro = {k: jdict['labels'][k] for k in self.ds.label_list}
                                         ^
SyntaxError: invalid syntax

Any ideas? Thanks.

**Comment by scttl** [comment]
Hi Thomas,

We're only supporting python 2.7 or later at this time.  Your error comes about because [dict comprehension](https://www.python.org/dev/peps/pep-0274/) was a feature that was added in 2.7, and we're making use of that on line 55.

**Comment by Thomas-Yang** [comment]
Hi Scott,

Thank you for your reply. I updated my python version to 2.7, now the CPU example works well. However, I got the following error when run the GPU example (neon --gpu cudanet examples/convnet/i1k-alexnet-fp32.yaml):

WARNING:neon.util.persist:deserializing object from:  examples/convnet/i1k-alexnet-fp32.yaml
WARNING:neon.datasets.imageset:Imageset initialized with dtype <type 'numpy.float32'>
2015-05-26 20:30:53,764 WARNING:neon - setting log level to: 20
2015-05-26 20:30:53,902 WARNING:__init__ - cudanet not found, can't run via GPU
Traceback (most recent call last):
  File "/usr/local/bin/neon", line 240, in <module>
    experiment, result, status = main()
  File "/usr/local/bin/neon", line 202, in main
    device_id=args.device_id)
  File "/usr/local/lib/python2.7/site-packages/neon/backends/__init__.py", line 157, in gen_backend
    raise RuntimeError("Can't find CUDA capable GPU")
RuntimeError: Can't find CUDA capable GPU

I have a K40 GPU installed on this machine. Do I have to install the cudanet, which is another project from nervana? (https://github.com/NervanaSystems/cuda-convnet2 <https://github.com/NervanaSystems/cuda-convnet2>)

Thanks!

**Comment by apark263** [comment]
Hi Thomas,

Yes, the Nervana cuda-convnet2 needs to be installed in order to run gpu backend examples on kepler cards.

-Alex

**Comment by Thomas-Yang** [comment]
I got the following error installing cudanet:

CMake Error at /usr/share/cmake/Modules/FindBLAS.cmake:594 (message):
  A required library with BLAS API not found.  Please specify library
  location.
Call Stack (most recent call first):
  CMakeLists.txt:36 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/thomas/cuda-convnet2/build/CMakeFiles/CMakeOutput.log".
See also "/home/thomas/cuda-convnet2/build/CMakeFiles/CMakeError.log”.

I have cublas and cudnn libraries installed under /usr/local/cuda/lib64/. The location is exposed to LD_LIBRARY_PATH env variable.

Any ideas?

Best

**Comment by ursk** [comment]
Hi Thomas,
cuda-convnet2 has a dependency on the ATLAS libraries which need to be installed separately. Please see the documentation at the original cuda-convnet2 project page for details: https://code.google.com/p/cuda-convnet2/wiki/Compiling

**Comment by Thomas-Yang** [comment]
Hi there,

I installed all the required libraries on the web page. However, it still complains missing BLAS library:

CMake Error at /usr/share/cmake/Modules/FindBLAS.cmake:594 (message):
  A required library with BLAS API not found.  Please specify library
  location.
Call Stack (most recent call first):
  CMakeLists.txt:36 (find_package)

all the installed libraries are listed below:

python-devel-2.6.6-52.el6.x86_64
numpy-1.4.1-9.el6.x86_64
scipy-0.7.2-8.el6.x86_64
python-magic-5.04-21.el6.x86_64
python-matplotlib-0.99.1.2-1.el6.x86_64
atlas-devel-3.8.4-2.el6.x86_64
libjpeg-turbo-devel-1.2.1-3.el6_5.x86_64
opencv-2.0.0-12.el6.x86_64
opencv-devel-2.0.0-12.el6.x86_64

Any thoughts?

**Comment by scttl** [comment]
Hi Thomas,

You may also need to add at least one of `blas-devel` or `openblas-devel`

If that still doesn't work you'll need to provide more information for us like the `CMakeOutput.log` and `CMakeError.log` from wherever cmake is building from in your environment

**Comment by Thomas-Yang** [comment]
Hi Scott,

I passed the blas error and followed the instruction on https://code.google.com/p/cuda-convnet2/wiki/Compiling <https://code.google.com/p/cuda-convnet2/wiki/Compiling> to install cudanet with build.sh.
However, I came across the following error complaining jpeg.

src/jpeg.cpp: In member function ‘void DecoderThread::decodeJpeg(int, int&, int&)’:
src/jpeg.cpp:74:37: error: ‘jpeg_mem_src’ was not declared in this scope
     jpeg_mem_src(&cinf, src, src_len);
                                     ^
make: *** [obj/release/./src/jpeg.cpp.o] Error 1

Any thoughts? 

Also what is the difference of cudanet on googlecode and github? Which one am I supposed to use?

**Comment by apark263** [comment]
Hi Thomas,

Please don't use the google code repository for compiling cuda-convnet2 if you plan to use the cudanet backend .  It is not compatible with neon and does not have the cudanet python interface.

Just grab the Nervana Systems cuda-convnet2 fork and use the pip install instructions.

(In addition to providing the cudanet python interface, we have made some modifications to the core cuda-convnet2)

**Comment by scttl** [comment]
Hi Thomas,

As to your current error, my hunch is that the version of libjpeg-devel that you have installed is too old.  I'd recommend upgrading this to something more recent.

**Comment by ursk** [comment]
Hi Thomas,

Note that the other libraries you listed, e.g.

python-devel-2.6.6-52.el6.x86_64
numpy-1.4.1-9.el6.x86_64

are also too old, the minimum version for python is 2.7 and the minimum numpy 1.8.1. We recommend Anaconda Python, or installing Python through Homebrew, to easily get the latest versions.

**Comment by Thomas-Yang** [comment]
Hi all,

Thank you for your reply. I am working on CentOS 6.6. I have updated python version to 2.7.10 as well as the numpy to be 1.9.2. After I switched back to Nervana cuda-convnet2, I got the initial missing blas library error:

CMake Error at /usr/share/cmake/Modules/FindBLAS.cmake:594 (message):
  A required library with BLAS API not found.  Please specify library
  location.
Call Stack (most recent call first):
  CMakeLists.txt:36 (find_package)

-- Configuring incomplete, errors occurred!

I guess the default path that makefile looks for does not contain the blas library. Is there a place I can specify the library path?, which should be the following:

# CUDA toolkit installation directory.
export CUDA_INSTALL_PATH=/usr/local/cuda

# Python include directory. This should contain the file Python.h, among others.
export PYTHON_INCLUDE_PATH=/usr/local/include/python2.7

# Numpy include directory. This should contain the file arrayobject.h, among others.
export NUMPY_INCLUDE_PATH=/usr/local/lib/python2.7/site-packages/numpy/core/include/numpy

# ATLAS library directory. This should contain the file libcblas.so, among others.
export ATLAS_LIB_PATH=/usr/lib64/atlas

This is how I passed the blas error with the googlecode version.

Best

**Comment by scttl** [comment]
You can pass a specific set of library paths into cmake via the `CMAKE_LIBRARY_PATH` environment variable (or include file paths via `CMAKE_INCLUDE_PATH`).  Perhaps running:

    export CMAKE_LIBRARY_PATH="${CMAKE_LIBRARY_PATH}:${ATLAS_LIB_PATH}"

first will get you unstuck on the BLAS lib error.

**Comment by hjchen2** [comment]
@ursk Hi ursk.  I have updated python version to 2.7.10, however it shows using python2.6 when I install neon once again. What can I do with this problem
![default](https://cloud.githubusercontent.com/assets/13991173/9512009/9b0b34e2-4caf-11e5-9e77-7a4fb0fa92d0.PNG)

**Comment by ursk** [comment]
Hi,
can you provide more information, what kind of system and which python distribution you are using? You might be better off opening a new issue for that, since this one has been closed for a while.

**Comment by hjchen2** [comment]
OK, Thanks
